version: '3.7'
services:
  discord-socket-client:
    build: discord_socket_client/.
    environment:
      - KAFKA_SERVER='redpanda'
      - KAFKA_PORT=29092
      - DISCORD_TOKEN=''
  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda-1
    ports:
    - 9092:9092
    - 29092:29092